### ISSUE TITLE
Feature request: amd64 builds

### ISSUE THREAD

**Issue by M-Gregoire** [RoggerFabri/mopidy-icesnap#19]
Hello,

First of all, thank you for your work! After trying out multiple `mopidy` images I'm really glad I found yours.

I've been able to manually build them for `amd64` and they work flawlessly. Unfortunately, It seems your pipeline only send the `arm` builds to Docker hub.

Would it be possible to also build and push the `amd64` docker images to Docker Hub, this would avoid the necessity of building them manually for future deployment.

Thank you,

**Comment by RoggerFabri** [comment]
Hi there, thanks for your feedback, I'm glad you found my images useful :) 
I have made available the `amd64` images as you requested, they're tagged as `<app>-amd64-latest`, please note that `snapserver` is broken at the moment for both `arm64v8` and `amd64` and will be fixed soon.

**Comment by RoggerFabri** [comment]
Good news! `snapserver` is now being built on `amd64` too, I'm closing this issue as all images are covered.
